/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env=development --include-runtime=false` (hash: 75482af33cbee43e9e58d26252a95ebb)
interface __BaseEnv_Env {
  ASSETS: Fetcher;
  VECTIS_CONVEX_SITE: "https://clear-hare-471.convex.site";
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("../web/worker");
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "VECTIS_CONVEX_SITE">> {}
}
