export const preparationCommands = [
  "environment.prepare-linux",
  "environment.resume",
  "environment.install-macos",
  "environment.resume-macos",
  "environment.open-macos-setup",
  "environment.connect-macos-guest",
  "environment.verify-macos-guest",
  "environment.finish-macos-setup",
  "environment.install-windows",
  "environment.resume-windows",
];
export const cancellableCommands = [
  "environment.install-macos",
  "environment.resume-macos",
  "environment.open-macos-setup",
  "environment.connect-macos-guest",
  "environment.verify-macos-guest",
  "environment.install-windows",
  "environment.resume-windows",
  "environment.prepare-linux",
  "environment.resume",
  "runner.run",
  "job.refresh",
  "job.scan",
  "migration.analyze",
  "migration.publish",
  "repository.connect",
];
export const commandLabels: Record<string, string> = {
  "environment.prepare-linux": "Prepare Linux image",
  "environment.resume": "Resume Linux preparation",
  "environment.install-macos": "Install macOS",
  "environment.resume-macos": "Resume macOS installation",
  "environment.open-macos-setup": "Open macOS setup console",
  "environment.connect-macos-guest": "Connect macOS guest SSH",
  "environment.verify-macos-guest": "Verify macOS guest SSH",
  "environment.finish-macos-setup": "Finish macOS setup",
  "environment.discard-macos": "Discard macOS setup",
  "environment.install-windows": "Install Windows",
  "environment.resume-windows": "Resume Windows installation",
  "environment.register": "Register environment",
  "environment.configure": "Configure environment",
  "environment.start": "Start clean VM",
  "instance.stop": "Stop VM",
  "instance.reconcile": "Reconcile VM",
  "runner.run": "Run runner",
  "runner.reconcile": "Reconcile runner",
  "repository.connect": "Connect repository",
  "repository.disconnect": "Disconnect repository",
  "repository.automatic": "Change automatic runners",
  "job.refresh": "Recover GitHub job",
  "job.scan": "Discover missing jobs",
  "migration.analyze": "Analyze workflow migration",
  "migration.publish": "Publish migration pull request",
  "migration.preview": "Preview workflow migration",
  "environment.remove": "Remove environment",
  "operation.cancel": "Close operation",
  "machine.pause": "Change VM intake",
};
// A setting is confirmed after it happened, so its message is what changed, not what was asked.
export const settingLabels: Record<string, string> = {
  "repository.automatic": "Automatic runners updated",
  "environment.configure": "Environment updated",
  "environment.register": "Environment registered",
  "environment.remove": "Environment removed",
  "instance.stop": "VM stopped",
  "instance.reconcile": "VM reconciled",
  "operation.cancel": "Operation closed",
  "machine.pause": "VM intake updated",
};
